'use client';

import { useState } from 'react';
import { RiDownloadLine, RiEyeLine } from 'react-icons/ri';
import Button from '@/components/ui/Button';

const STUDENT_OPTIONS = [
  { value: '645020082-4', label: 'Joanna Sofia (645020082-4)' },
  { value: '665380017-0', label: 'Cristina Sofia (665380017-0)' },
  { value: '645020081-6', label: 'Monica Sofia (645020081-6)' },
];

const TEMPLATE_OPTIONS = [
  { value: 'leave_request',         label: 'Leave Request Form' },
  { value: 'enrollment_certificate', label: 'Enrollment Certificate' },
  { value: 'travel_letter',          label: 'Travel Letter' },
];

const mockGenerated = [
  { id: 1, student: 'Joanna Sofia',   template: 'Leave Request Form',     generatedDate: '10/03/2025', generatedBy: 'Staff Kasama' },
  { id: 2, student: 'Cristina Sofia', template: 'Enrollment Certificate', generatedDate: '08/03/2025', generatedBy: 'Staff Kasama' },
  { id: 3, student: 'Monica Sofia',   template: 'Travel Letter',          generatedDate: '05/03/2025', generatedBy: 'Staff Kasama' },
];

export default function StaffDocumentsPage() {
  const [selectedStudent,  setSelectedStudent]  = useState('');
  const [selectedTemplate, setSelectedTemplate] = useState('');
  const [generated,        setGenerated]        = useState(false);

  const handleGenerate = () => {
    if (selectedStudent && selectedTemplate) {
      setGenerated(true);
    }
  };

  return (
    <div className="flex flex-col gap-6">
      <p className="text-2xl font-semibold text-primary">Document Management</p>

      <div className="flex flex-col lg:flex-row gap-6">

        {/* LEFT: Generate Document Form */}
        <div className="lg:w-80 shrink-0">
          <div className="bg-white rounded-2xl shadow-sm p-6 flex flex-col gap-5">
            <p className="text-base font-semibold text-primary">Generate Document</p>
            <hr />

            {/* Select Student */}
            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-medium text-primary/50">Select Student</label>
              <select
                value={selectedStudent}
                onChange={e => { setSelectedStudent(e.target.value); setGenerated(false); }}
                className="border border-gray-200 rounded-xl px-3 py-2.5 text-sm text-primary bg-gray-50 outline-none cursor-pointer hover:border-primary transition-colors"
              >
                <option value="" disabled>Select student...</option>
                {STUDENT_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
              </select>
            </div>

            {/* Select Template */}
            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-medium text-primary/50">Select Template</label>
              <select
                value={selectedTemplate}
                onChange={e => { setSelectedTemplate(e.target.value); setGenerated(false); }}
                className="border border-gray-200 rounded-xl px-3 py-2.5 text-sm text-primary bg-gray-50 outline-none cursor-pointer hover:border-primary transition-colors"
              >
                <option value="" disabled>Select template...</option>
                {TEMPLATE_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
              </select>
            </div>

            {/* Generate Button */}
            <Button
              variant="primary"
              label="Generate Document"
              onClick={handleGenerate}
              className="w-full justify-center"
            />

            {/* Success State */}
            {generated && (
              <div className="bg-green-50 border border-green-200 rounded-xl px-4 py-3 text-sm text-green-700 font-medium text-center">
                Document generated successfully!
              </div>
            )}
          </div>
        </div>

        {/* RIGHT: Generated Documents History */}
        <div className="flex-1 bg-white rounded-2xl shadow-sm p-6 flex flex-col gap-5">
          <p className="text-base font-semibold text-primary">Generated Documents</p>
          <div className="overflow-x-auto">
            <table className="w-full text-sm border-t">
              <thead>
                <tr className="border-b">
                  <th className="text-left   py-4 px-4 font-semibold text-primary">Student</th>
                  <th className="text-left   py-4 px-4 font-semibold text-primary">Template</th>
                  <th className="text-left   py-4 px-4 font-semibold text-primary">Generated Date</th>
                  <th className="text-left   py-4 px-4 font-semibold text-primary">Generated By</th>
                  <th className="text-center py-4 px-4 font-semibold text-primary">Action</th>
                </tr>
              </thead>
              <tbody>
                {mockGenerated.map(doc => (
                  <tr key={doc.id} className="border-b last:border-none hover:bg-gray-50 transition">
                    <td className="py-3 px-4 text-primary font-medium">{doc.student}</td>
                    <td className="py-3 px-4 text-primary">{doc.template}</td>
                    <td className="py-3 px-4 text-primary">{doc.generatedDate}</td>
                    <td className="py-3 px-4 text-gray-500">{doc.generatedBy}</td>
                    <td className="py-3 px-4 text-center">
                      <div className="flex items-center justify-center gap-2">
                        <Button variant="ghost" label="Download" icon={RiDownloadLine} onClick={() => {}} />
                        <Button variant="info"  onClick={() => {}} />
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

      </div>
    </div>
  );
}
